"""initial migration

Revision ID: 55984fd6c02c
Revises: 
Create Date: 2024-04-10 21:02:13.367591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55984fd6c02c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
